plugins {
    id "fabric-loom" version "${fabric_loom_version}"
}

base {
    archivesName = "can-pipe-fabric-"+minecraft_version
}

repositories {
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.org"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = uri("https://api.modrinth.com/maven")
            }
        }
        filter {
            includeGroup("maven.modrinth")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    modImplementation fabricApi.module("fabric-resource-loader-v0", fabric_version)
    modImplementation fabricApi.module("fabric-api-base", fabric_version)
    modImplementation fabricApi.module("fabric-key-binding-api-v1", fabric_version)
    modImplementation fabricApi.module("fabric-renderer-indigo", fabric_version)

    include fabricApi.module("fabric-resource-loader-v0", fabric_version)
    include fabricApi.module("fabric-api-base", fabric_version)
    include fabricApi.module("fabric-key-binding-api-v1", fabric_version)

    modImplementation "blue.endless:jankson:1.2.3"
    include "blue.endless:jankson:1.2.3"

    // modImplementation "com.terraformersmc:modmenu:13.0.2"
    // modImplementation "maven.modrinth:sodium:mc1.21.5-0.6.13-fabric"
    // modImplementation fabricApi.module("fabric-block-view-api-v2", fabric_version)
    // modImplementation fabricApi.module("fabric-rendering-data-attachment-v1", fabric_version)
    // modImplementation fabricApi.module("fabric-rendering-fluids-v1", fabric_version)

    // modImplementation "maven.modrinth:debug-keybind:15.0.0-fabric"
    // modImplementation "maven.modrinth:boxlib:7lzlZrX9"
}

compileJava.source project(":common").sourceSets.main.allSource

loom {
    accessWidenerPath = file("src/main/resources/canpipe.accesswidener")

    mixin {
        useLegacyMixinAp = false
    }

    runs {
        client {
            client()
            setConfigName 'Fabric'
            ideConfigGenerated true
            runDir '../run'
            appendProjectPathToConfigName = false
            programArg "--renderDebugLabels"
            vmArgs "-Dmixin.debug=true"
        }
    }
}

processResources {
    from project(":common").sourceSets.main.resources

    var expandProps = [
        'version'                      : version,
        'minecraft_version'            : fabric_minecraft_version,
        'mod_name'                     : mod_name,
        'mod_author'                   : mod_author,
        'mod_id'                       : mod_id,
        'license'                      : license,
        'description'                  : project.description
    ]

    filesMatching("fabric.mod.json") {
        expand expandProps
    }
    inputs.properties(expandProps)
}