plugins {
    id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
}

base {
    archivesName = "can-pipe-fabric-"+minecraft_version
}

repositories {
    mavenLocal()
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.org"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com"
    }
    maven {
        name= "RogueLogix"
        url = "https://maven.logix.dev/snapshots"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = uri("https://api.modrinth.com/maven")
            }
        }
        filter {
            includeGroup("maven.modrinth")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    implementation fabricApi.module("fabric-resource-loader-v0", fabric_version)
    implementation fabricApi.module("fabric-resource-loader-v1", fabric_version)
    implementation fabricApi.module("fabric-api-base", fabric_version)
    implementation fabricApi.module("fabric-key-mapping-api-v1", fabric_version)
    // implementation fabricApi.module("fabric-renderer-indigo", fabric_version)

    include fabricApi.module("fabric-resource-loader-v0", fabric_version)
    include fabricApi.module("fabric-resource-loader-v1", fabric_version)
    include fabricApi.module("fabric-api-base", fabric_version)
    include fabricApi.module("fabric-key-mapping-api-v1", fabric_version)

    implementation "blue.endless:jankson:1.2.3"
    include "blue.endless:jankson:1.2.3"

    if (System.getenv("WITH_CINNABAR") == "1") {
        implementation "graphics.cinnabar:cinnabar-fabric:${cinnabar_version}"
    }
    else {
        compileOnly "graphics.cinnabar:cinnabar-fabric:${cinnabar_version}"
    }
}

compileJava.source project(":common").sourceSets.main.allSource

loom {
    accessWidenerPath = file("src/main/resources/canpipe.accesswidener")

    mixin {
        useLegacyMixinAp = false
    }

    runs {
        client {
            client()
            setConfigName "Fabric"
            ideConfigGenerated true
            runDir "../run"
            appendProjectPathToConfigName = false
            // programArg "--renderDebugLabels"
            // programArg "--tracy"
            // vmArg "-XX:-Inline"
            properties([
                "mixin.debug": "true",
                // "cinnabar.vulkanValidationLayers": "true",
                // "cinnabar.debugLogging": "true"
            ])
        }
    }
}

processResources {
    from project(":common").sourceSets.main.resources

    var expandProps = [
        'version'                      : version,
        'minecraft_version'            : fabric_minecraft_version,
        'mod_name'                     : mod_name,
        'mod_author'                   : mod_author,
        'mod_id'                       : mod_id,
        'license'                      : license,
        'description'                  : project.description
    ]

    filesMatching("fabric.mod.json") {
        expand expandProps
    }
    inputs.properties(expandProps)
}