plugins {
    id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
}

base {
    archivesName = "can-pipe-fabric-"+minecraft_version
}

repositories {
    mavenLocal()
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.org"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com"
    }
    maven {
        name= "RogueLogix"
        url = "https://maven.logix.dev/snapshots"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = uri("https://api.modrinth.com/maven")
            }
        }
        filter {
            includeGroup("maven.modrinth")
        }
    }
}

configurations {
    cinnabar
    compileOnly.extendsFrom cinnabar
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    implementation fabricApi.module("fabric-resource-loader-v0", fabric_version)
    implementation fabricApi.module("fabric-resource-loader-v1", fabric_version)
    implementation fabricApi.module("fabric-api-base", fabric_version)
    implementation fabricApi.module("fabric-key-mapping-api-v1", fabric_version)
    /*implementation*/ compileOnly fabricApi.module("fabric-renderer-indigo", /*fabric_version*/ "0.141.3+1.21.11")

    include fabricApi.module("fabric-resource-loader-v0", fabric_version)
    include fabricApi.module("fabric-resource-loader-v1", fabric_version)
    include fabricApi.module("fabric-api-base", fabric_version)
    include fabricApi.module("fabric-key-mapping-api-v1", fabric_version)

    implementation "blue.endless:jankson:1.2.3"
    include "blue.endless:jankson:1.2.3"

    cinnabar "graphics.cinnabar:cinnabar-fabric:${cinnabar_version}"
}

compileJava.source project(":common").sourceSets.main.allSource

loom {
    accessWidenerPath = file("src/main/resources/canpipe.accesswidener")

    mixin {
        useLegacyMixinAp = false
    }

    mods {
        "canpipe" {
            sourceSet sourceSets.main
            sourceSet("main", ":common")
        }
    }

    runs {
        client {
            client()
            setConfigName "Fabric"
            ideConfigGenerated true
            runDir "../run"
            vmArg "-XX:+UnlockDiagnosticVMOptions"
            vmArg "-XX:+DebugNonSafepoints"
            properties([
                "mixin.debug": "true",
            ])
            appendProjectPathToConfigName = false
        }
        clientCinnabar {
            inherit client
            runDir "../run"
            setConfigName "Fabric Cinnabar"
            properties([
                "fabric.addMods": project.configurations.cinnabar.getFiles()
                    .stream().map({f -> f.getAbsolutePath()})
                    .collect(java.util.stream.Collectors.joining(File.pathSeparator))
            ])
        }
        clientCinnabarValidated {
            inherit client
            runDir "../run"
            setConfigName "Fabric Cinnabar Validated"
            properties([
                "cinnabar.vulkanValidationLayers": "true"
            ])
        }
    }
}

processResources {
    from project(":common").sourceSets.main.resources

    var expandProps = [
        'version'                      : version,
        'minecraft_version'            : fabric_minecraft_version,
        'mod_name'                     : mod_name,
        'mod_author'                   : mod_author,
        'mod_id'                       : mod_id,
        'license'                      : license,
        'description'                  : project.description
    ]

    filesMatching("fabric.mod.json") {
        expand expandProps
    }
    inputs.properties(expandProps)
}