version=0.4.8
group=fewizz.canpipe
java_version=25

minecraft_version=26.2
mod_name=Can-Pipe
mod_author=fewizz
mod_id=canpipe
license=LGPL-3.0
credits=
description=Mod for loading Canvas pipelines

# Fabric
fabric_minecraft_version=~26.2
# https://maven.fabricmc.net/net/fabricmc/fabric-loom/
fabric_loom_version=1.17.9
# https://maven.fabricmc.net/net/fabricmc/fabric-loader/
fabric_loader_version=0.19.3
# https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/
fabric_version=0.154.2+26.2

# NeoForge
neoforge_minecraft_version_range=[26.2,26.3)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
# https://projects.neoforged.net/neoforged/moddevgradle
mod_dev_gradle_version=2.0.143
# https://projects.neoforged.net/neoforged/neoforge
neoforge_current_version=26.2.0.37-beta
neoforge_minimal_version=26.2.0.0-beta
neoforge_loader_version_range=[4,)

# Misc Gradle settings
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
fabric.loom.multiProjectOptimisation=true
