version=0.4.3
group=fewizz.canpipe
java_version=25

minecraft_version=26.1.2
mod_name=Can-Pipe
mod_author=fewizz
mod_id=canpipe
license=LGPL-3.0
credits=
description=Mod for loading Canvas pipelines

# Fabric
fabric_minecraft_version=~26.1
# https://maven.fabricmc.net/net/fabricmc/fabric-loom/
fabric_loom_version=1.16.1
# https://maven.fabricmc.net/net/fabricmc/fabric-loader/
fabric_loader_version=0.19.2
# https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/
fabric_version=0.146.1+26.1.2

# NeoForge
neoforge_minecraft_version_range=[26.1,26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
# https://projects.neoforged.net/neoforged/moddevgradle
mod_dev_gradle_version=2.0.141
# https://projects.neoforged.net/neoforged/neoforge
neoforge_current_version=26.1.2.27-beta
neoforge_minimal_version=26.1.0.0-beta
neoforge_loader_version_range=[4,)

# https://maven.logix.dev/#/
cinnabar_version=26.1.1-0.0.7-beta-92-gc6f31c3

# Misc Gradle settings
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
fabric.loom.multiProjectOptimisation=true
