version=0.2.0
group=fewizz.canpipe
java_version=21

minecraft_version=1.21.7
mod_name=Can-Pipe
mod_author=fewizz
mod_id=canpipe
license=LGPL-3.0
credits=
description=Mod for loading Canvas pipelines

# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.6
parchment_version=2025.06.29

# Fabric
fabric_version=0.129.0+1.21.7
fabric_loader_version=0.16.14

# NeoForge
neoforge_minecraft_version_range=[1.21.7]
neoforge_current_version=21.7.25-beta
neoforge_minimal_version=21.7.0-beta
neoforge_loader_version_range=[4,)
neo_form_version=1.21.7-20250630.141722

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

fabric.loom.multiProjectOptimisation=true
