const int frx_matEmissive = 0;  // TODO define
const int frx_matCutout = 0;  // TODO define
const int frx_matUnmipped = 0;  // TODO define
const int frx_matDisableAo = 0;  // TODO define
const int frx_matDisableDiffuse = 0;  // TODO define
const int frx_matHurt = 0;  // TODO define
const int frx_matFlash = 0;  // TODO define
const int frx_matGlint = 0;  // TODO define
const int frx_matGlintEntity = 0;  // unused?
const float frx_matExposure = 0.0;  // unused?