plugins {
    id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
}

loom {
    accessWidenerPath = new File(rootDir, "fabric/src/main/resources/canpipe.accesswidener")
    runs {}
}

repositories {
    mavenLocal()
    maven { url "https://maven.shedaniel.me/" }
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.org"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = uri("https://api.modrinth.com/maven")
            }
        }
        filter {
            includeGroup("maven.modrinth")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    compileOnly "blue.endless:jankson:1.2.3"

    compileOnly "maven.modrinth:rrtt217-s-hdr-mod:3.1.1-26.2+fabric"
    compileOnly("me.shedaniel.cloth:cloth-config-fabric:26.2.155") { exclude(group: "net.fabricmc.fabric-api") }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}